version: '3.8'

services:
  catalogservice:
    image: rasmusdd/catalogservicegit-image:latest
    container_name: catalogservice
    hostname: catalogservice
    ports:
      - 81:8080
    environment:
      - ConnectionString=mongodb://admin:1234@mongodb:27017
      - DatabaseName=4SemProj
      - collectionName=Katalog
    networks:
      - auctionnetwork

networks:
  auctionnetwork:
    name: auctionnetwork
    external: true